// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Personal_Expense_Tracking_System_Web_Api.Data;

#nullable disable

namespace Personal_Expense_Tracking_System_Web_Api.Migrations
{
    [DbContext(typeof(ApplicationDB))]
    [Migration("20240331060537_SeedingAndCreatingExpenseCategoriesTable")]
    partial class SeedingAndCreatingExpenseCategoriesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Personal_Expense_Tracking_System_Web_Api.Models.Categories", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Salary"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Freelancing"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Invesments"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Stocks"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Bitcoin"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Bank Transfer"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Youtube"
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Other"
                        });
                });

            modelBuilder.Entity("Personal_Expense_Tracking_System_Web_Api.Models.ExpenseCategories", b =>
                {
                    b.Property<int>("ExpenseCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseCategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExpenseCategoryID");

                    b.ToTable("expenseCategories");

                    b.HasData(
                        new
                        {
                            ExpenseCategoryID = 1,
                            CategoryName = "Education"
                        },
                        new
                        {
                            ExpenseCategoryID = 2,
                            CategoryName = "Groceries"
                        },
                        new
                        {
                            ExpenseCategoryID = 3,
                            CategoryName = "Health"
                        },
                        new
                        {
                            ExpenseCategoryID = 4,
                            CategoryName = "Subscriptions"
                        },
                        new
                        {
                            ExpenseCategoryID = 5,
                            CategoryName = "Takeaways"
                        },
                        new
                        {
                            ExpenseCategoryID = 6,
                            CategoryName = "Clothing"
                        },
                        new
                        {
                            ExpenseCategoryID = 7,
                            CategoryName = "Travelling"
                        },
                        new
                        {
                            ExpenseCategoryID = 8,
                            CategoryName = "Other"
                        });
                });

            modelBuilder.Entity("Personal_Expense_Tracking_System_Web_Api.Models.Incomes", b =>
                {
                    b.Property<int>("IncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncomeId"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SalaryAmount")
                        .HasColumnType("float");

                    b.Property<string>("SalaryTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IncomeId");

                    b.HasIndex("CategoryID");

                    b.ToTable("incomes");

                    b.HasData(
                        new
                        {
                            IncomeId = 1,
                            CategoryID = 5,
                            Date = new DateTime(2024, 3, 31, 12, 5, 37, 330, DateTimeKind.Local).AddTicks(7129),
                            Reference = "From freelance works.",
                            SalaryAmount = 1300.0,
                            SalaryTitle = "From Freelance"
                        },
                        new
                        {
                            IncomeId = 2,
                            CategoryID = 3,
                            Date = new DateTime(2024, 3, 31, 12, 5, 37, 330, DateTimeKind.Local).AddTicks(7146),
                            Reference = "My January Spotify earnings.",
                            SalaryAmount = 8000.0,
                            SalaryTitle = "Spotify"
                        },
                        new
                        {
                            IncomeId = 3,
                            CategoryID = 7,
                            Date = new DateTime(2024, 3, 31, 12, 5, 37, 330, DateTimeKind.Local).AddTicks(7148),
                            Reference = "My January youtube earnings.",
                            SalaryAmount = 1200.0,
                            SalaryTitle = "Youtube Adsense"
                        },
                        new
                        {
                            IncomeId = 4,
                            CategoryID = 1,
                            Date = new DateTime(2024, 3, 31, 12, 5, 37, 330, DateTimeKind.Local).AddTicks(7149),
                            Reference = "My January developer salary.",
                            SalaryAmount = 6000.0,
                            SalaryTitle = "Developer Salary"
                        });
                });

            modelBuilder.Entity("Personal_Expense_Tracking_System_Web_Api.Models.Incomes", b =>
                {
                    b.HasOne("Personal_Expense_Tracking_System_Web_Api.Models.Categories", "Categories")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
