// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Personal_Expense_Tracking_System_Web_Api.Data;

#nullable disable

namespace Personal_Expense_Tracking_System_Web_Api.Migrations
{
    [DbContext(typeof(ApplicationDB))]
    [Migration("20240312153145_seedingExpenseCategoriesAndExpensesTable")]
    partial class seedingExpenseCategoriesAndExpensesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Personal_Expense_Tracking_System_Web_Api.Models.Categories", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Salary"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Freelancing"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Invesments"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Stocks"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Bitcoin"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Bank Transfer"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Youtube"
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Other"
                        });
                });

            modelBuilder.Entity("Personal_Expense_Tracking_System_Web_Api.Models.ExpenseCategories", b =>
                {
                    b.Property<int>("ExpenseCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseCategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExpenseCategoryID");

                    b.ToTable("expenseCategories");

                    b.HasData(
                        new
                        {
                            ExpenseCategoryID = 1,
                            CategoryName = "Education"
                        },
                        new
                        {
                            ExpenseCategoryID = 2,
                            CategoryName = "Groceries"
                        },
                        new
                        {
                            ExpenseCategoryID = 3,
                            CategoryName = "Health"
                        },
                        new
                        {
                            ExpenseCategoryID = 4,
                            CategoryName = "Subscriptions"
                        },
                        new
                        {
                            ExpenseCategoryID = 5,
                            CategoryName = "Takeaways"
                        },
                        new
                        {
                            ExpenseCategoryID = 6,
                            CategoryName = "Clothing"
                        },
                        new
                        {
                            ExpenseCategoryID = 7,
                            CategoryName = "Travelling"
                        },
                        new
                        {
                            ExpenseCategoryID = 8,
                            CategoryName = "Other"
                        });
                });

            modelBuilder.Entity("Personal_Expense_Tracking_System_Web_Api.Models.Expenses", b =>
                {
                    b.Property<int>("ExpenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseID"));

                    b.Property<double>("ExpenseAmount")
                        .HasColumnType("float");

                    b.Property<int>("ExpenseCategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpenseReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpenseTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExpenseID");

                    b.HasIndex("ExpenseCategoryID");

                    b.ToTable("expenses");

                    b.HasData(
                        new
                        {
                            ExpenseID = 1,
                            ExpenseAmount = 120.0,
                            ExpenseCategoryID = 3,
                            ExpenseDate = new DateTime(2024, 3, 12, 21, 31, 44, 800, DateTimeKind.Local).AddTicks(6781),
                            ExpenseReference = "Tooth removal",
                            ExpenseTitle = "Dentiest Appointment"
                        },
                        new
                        {
                            ExpenseID = 2,
                            ExpenseAmount = 3000.0,
                            ExpenseCategoryID = 7,
                            ExpenseDate = new DateTime(2024, 3, 12, 21, 31, 44, 800, DateTimeKind.Local).AddTicks(6783),
                            ExpenseReference = "Went to Spain",
                            ExpenseTitle = "Travelling"
                        },
                        new
                        {
                            ExpenseID = 3,
                            ExpenseAmount = 800.0,
                            ExpenseCategoryID = 8,
                            ExpenseDate = new DateTime(2024, 3, 12, 21, 31, 44, 800, DateTimeKind.Local).AddTicks(6785),
                            ExpenseReference = "Rent and bills",
                            ExpenseTitle = "Rent"
                        });
                });

            modelBuilder.Entity("Personal_Expense_Tracking_System_Web_Api.Models.Incomes", b =>
                {
                    b.Property<int>("IncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncomeId"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SalaryAmount")
                        .HasColumnType("float");

                    b.HasKey("IncomeId");

                    b.HasIndex("CategoryID");

                    b.ToTable("incomes");

                    b.HasData(
                        new
                        {
                            IncomeId = 1,
                            CategoryID = 5,
                            Date = new DateTime(2024, 3, 12, 21, 31, 44, 800, DateTimeKind.Local).AddTicks(6694),
                            Reference = "Bitcoin money",
                            SalaryAmount = 2000.0
                        },
                        new
                        {
                            IncomeId = 2,
                            CategoryID = 3,
                            Date = new DateTime(2024, 3, 12, 21, 31, 44, 800, DateTimeKind.Local).AddTicks(6710),
                            Reference = "Spotify",
                            SalaryAmount = 8000.0
                        },
                        new
                        {
                            IncomeId = 3,
                            CategoryID = 7,
                            Date = new DateTime(2024, 3, 12, 21, 31, 44, 800, DateTimeKind.Local).AddTicks(6711),
                            Reference = "Youtube Addsense",
                            SalaryAmount = 1200.0
                        },
                        new
                        {
                            IncomeId = 4,
                            CategoryID = 1,
                            Date = new DateTime(2024, 3, 12, 21, 31, 44, 800, DateTimeKind.Local).AddTicks(6713),
                            Reference = "Developer Salary",
                            SalaryAmount = 6000.0
                        });
                });

            modelBuilder.Entity("Personal_Expense_Tracking_System_Web_Api.Models.Expenses", b =>
                {
                    b.HasOne("Personal_Expense_Tracking_System_Web_Api.Models.ExpenseCategories", "ExpenseCategories")
                        .WithMany()
                        .HasForeignKey("ExpenseCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseCategories");
                });

            modelBuilder.Entity("Personal_Expense_Tracking_System_Web_Api.Models.Incomes", b =>
                {
                    b.HasOne("Personal_Expense_Tracking_System_Web_Api.Models.Categories", "Categories")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
