// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Personal_Expense_Tracking_System_Web_Api.Data;

#nullable disable

namespace Personal_Expense_Tracking_System_Web_Api.Migrations
{
    [DbContext(typeof(ApplicationDB))]
    partial class ApplicationDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Personal_Expense_Tracking_System_Web_Api.Models.Categories", b =>
                {
                    b.Property<long>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1L,
                            CategoryName = "Salary"
                        },
                        new
                        {
                            CategoryID = 2L,
                            CategoryName = "Freelancing"
                        },
                        new
                        {
                            CategoryID = 3L,
                            CategoryName = "Invesments"
                        },
                        new
                        {
                            CategoryID = 4L,
                            CategoryName = "Stocks"
                        },
                        new
                        {
                            CategoryID = 5L,
                            CategoryName = "Bitcoin"
                        },
                        new
                        {
                            CategoryID = 6L,
                            CategoryName = "Bank Transfer"
                        },
                        new
                        {
                            CategoryID = 7L,
                            CategoryName = "Youtube"
                        },
                        new
                        {
                            CategoryID = 8L,
                            CategoryName = "Other"
                        });
                });

            modelBuilder.Entity("Personal_Expense_Tracking_System_Web_Api.Models.ExpenseCategories", b =>
                {
                    b.Property<long>("ExpenseCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ExpenseCategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExpenseCategoryID");

                    b.ToTable("expenseCategories");

                    b.HasData(
                        new
                        {
                            ExpenseCategoryID = 1L,
                            CategoryName = "Education"
                        },
                        new
                        {
                            ExpenseCategoryID = 2L,
                            CategoryName = "Groceries"
                        },
                        new
                        {
                            ExpenseCategoryID = 3L,
                            CategoryName = "Health"
                        },
                        new
                        {
                            ExpenseCategoryID = 4L,
                            CategoryName = "Subscriptions"
                        },
                        new
                        {
                            ExpenseCategoryID = 5L,
                            CategoryName = "Takeaways"
                        },
                        new
                        {
                            ExpenseCategoryID = 6L,
                            CategoryName = "Clothing"
                        },
                        new
                        {
                            ExpenseCategoryID = 7L,
                            CategoryName = "Travelling"
                        },
                        new
                        {
                            ExpenseCategoryID = 8L,
                            CategoryName = "Other"
                        });
                });

            modelBuilder.Entity("Personal_Expense_Tracking_System_Web_Api.Models.Expenses", b =>
                {
                    b.Property<long>("ExpenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ExpenseID"));

                    b.Property<double>("ExpenseAmount")
                        .HasColumnType("float");

                    b.Property<long>("ExpenseCategoryID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpenseReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpenseTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ExpenseID");

                    b.HasIndex("ExpenseCategoryID");

                    b.HasIndex("UserID");

                    b.ToTable("expenses");

                    b.HasData(
                        new
                        {
                            ExpenseID = 1L,
                            ExpenseAmount = 120.0,
                            ExpenseCategoryID = 3L,
                            ExpenseDate = new DateTime(2024, 6, 16, 14, 10, 24, 385, DateTimeKind.Local).AddTicks(9871),
                            ExpenseReference = "Tooth removal",
                            ExpenseTitle = "Dentiest Appointment",
                            UserID = 1L
                        },
                        new
                        {
                            ExpenseID = 2L,
                            ExpenseAmount = 3000.0,
                            ExpenseCategoryID = 7L,
                            ExpenseDate = new DateTime(2024, 6, 16, 14, 10, 24, 385, DateTimeKind.Local).AddTicks(9874),
                            ExpenseReference = "Went to Spain",
                            ExpenseTitle = "Travelling",
                            UserID = 1L
                        },
                        new
                        {
                            ExpenseID = 3L,
                            ExpenseAmount = 800.0,
                            ExpenseCategoryID = 8L,
                            ExpenseDate = new DateTime(2024, 6, 16, 14, 10, 24, 385, DateTimeKind.Local).AddTicks(9875),
                            ExpenseReference = "Rent and bills",
                            ExpenseTitle = "Rent",
                            UserID = 1L
                        });
                });

            modelBuilder.Entity("Personal_Expense_Tracking_System_Web_Api.Models.Incomes", b =>
                {
                    b.Property<long>("IncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IncomeId"));

                    b.Property<long>("CategoryID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SalaryAmount")
                        .HasColumnType("float");

                    b.Property<string>("SalaryTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("IncomeId");

                    b.HasIndex("CategoryID");

                    b.HasIndex("UserID");

                    b.ToTable("incomes");

                    b.HasData(
                        new
                        {
                            IncomeId = 1L,
                            CategoryID = 5L,
                            Date = new DateTime(2024, 6, 16, 14, 10, 24, 385, DateTimeKind.Local).AddTicks(9661),
                            Reference = "From freelance works.",
                            SalaryAmount = 1300.0,
                            SalaryTitle = "From Freelance",
                            UserID = 1L
                        },
                        new
                        {
                            IncomeId = 2L,
                            CategoryID = 3L,
                            Date = new DateTime(2024, 6, 16, 14, 10, 24, 385, DateTimeKind.Local).AddTicks(9774),
                            Reference = "My January Spotify earnings.",
                            SalaryAmount = 8000.0,
                            SalaryTitle = "Spotify",
                            UserID = 1L
                        },
                        new
                        {
                            IncomeId = 3L,
                            CategoryID = 7L,
                            Date = new DateTime(2024, 6, 16, 14, 10, 24, 385, DateTimeKind.Local).AddTicks(9776),
                            Reference = "My January youtube earnings.",
                            SalaryAmount = 1200.0,
                            SalaryTitle = "Youtube Adsense",
                            UserID = 1L
                        },
                        new
                        {
                            IncomeId = 4L,
                            CategoryID = 1L,
                            Date = new DateTime(2024, 6, 16, 14, 10, 24, 385, DateTimeKind.Local).AddTicks(9778),
                            Reference = "My January developer salary.",
                            SalaryAmount = 6000.0,
                            SalaryTitle = "Developer Salary",
                            UserID = 1L
                        });
                });

            modelBuilder.Entity("Personal_Expense_Tracking_System_Web_Api.Models.User", b =>
                {
                    b.Property<long>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            UserID = 1L,
                            Email = "rafisiddique652@gmail.com",
                            FirstName = "Rafi",
                            Gender = "Male",
                            LastName = "Siddique",
                            Password = "AQAAAAIAAYagAAAAEG77S3e8PORaUifTr4OagonyYgjgBgMYY4oCDlEXLY9TKy1jWp8dy7T3ym19aTwocw==",
                            UserName = "Admin",
                            UserPhoto = "rafi.jpg",
                            UserRole = "Admin"
                        });
                });

            modelBuilder.Entity("Personal_Expense_Tracking_System_Web_Api.Models.Expenses", b =>
                {
                    b.HasOne("Personal_Expense_Tracking_System_Web_Api.Models.ExpenseCategories", "ExpenseCategories")
                        .WithMany()
                        .HasForeignKey("ExpenseCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Personal_Expense_Tracking_System_Web_Api.Models.User", "Users")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseCategories");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Personal_Expense_Tracking_System_Web_Api.Models.Incomes", b =>
                {
                    b.HasOne("Personal_Expense_Tracking_System_Web_Api.Models.Categories", "Categories")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Personal_Expense_Tracking_System_Web_Api.Models.User", "Users")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categories");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
